SELECT
    SUM(CASE WHEN [FINAL] IS NULL THEN 1 ELSE 0 END) AS [FINAL_NULL件数]
    ,SUM(CASE WHEN [原価] IS NULL THEN 1 ELSE 0 END) AS [原価_NULL件数]
    ,SUM(CASE WHEN [FINAL] IS NOT NULL AND [原価] IS NOT NULL  THEN 1 ELSE 0 END) AS [2テーブルどちらにも存在する件数]
    ,COUNT(*) AS [全件数]
FROM
      tbl